#=========================================================
# title: pddyrdbrd spacevim.d customization
# filename: init.toml
# author: Paddy Redbeard <paddyredbeard at protonmail.com>
# license: GPLv3
# adapted_from: dark_powered.toml by Wang Shidong
#=========================================================

# All SpaceVim option below [option] section
[options]
    buffer_index_type = 4
    colorscheme = "molokai"
    colorscheme_bg = "dark"
    enable_guicolors = true
    enable_statusline_mode = false
    enable_tabline_filetype_icon = true
    filetree_direction = "left"
    guifont = "SourceCodePro Nerd Font Mono:h13"
    project_rooter_outermost = false
    relativenumber = false
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    statusline_inactive_separator = "arrow"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'core'
filetree_show_hidden = true
enable_vimfiler_gitstatus = true
enable_filetree_gitstatus = true

[[layers]]
name = 'git'
git_plugin = 'git'

[[layers]]
name = 'github'

[[layers]]
name = 'lang#html'

[[layers]]
name = 'lang#javascript'

[[layers]]
name = 'lang#php'

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'VersionControl'

[[custom_plugins]]
repo = "cespare/vim-toml"
merged = false

[[custom_plugins]]
repo = "editorconfig/editorconfig-vim"
merged = false

[[custom_plugins]]
repo = "junegunn/vim-github-dashboard"
merged = false

[[custom_plugins]]
repo = "nanotech/jellybeans.vim"
merged = false

[[custom_plugins]]
repo = "sjl/badwolf"
merged = false

[[custom_plugins]]
repo = "tpope/vim-vividchalk"
merged = false

